GuessBook.Web/Controllers/QuestionsController.cs
using System;
using System.Linq;
using GuessBook.EF.Context;
using GuessBook.Business.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using GuessBook.Business.Managers;
using System.Security.Claims;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace GuessBook.Web.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly IQuestionsService _questionsService;
        private readonly IOptionsService _optionsService;

        public QuestionsController(IQuestionsService questionsService, IOptionsService optionsService)
        {
            _questionsService = questionsService;
            _optionsService = optionsService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SaveOptionsAsync([FromBody] MemberAnswersDto model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception("Model state is not valid!");

                var question = (await _questionsService.GetQuestionByIdAsync(model.QuestionId)).ValueResult;
                if (question == null) throw new Exception("Something went wrong!");

                var optionIds = JsonConvert.DeserializeObject<List<string>>(model.OptionIds);
                var count = optionIds.Count;

                if (question != null)
                    switch (question.QType)
                    {
                        case 1:
                        case 3:
                            if (count < question.MinSelect || count > question.MaxSelect)
                            {
                                return BadRequest(
                                    $"Min {question.MinSelect} - Max {question.MaxSelect} items must be selected!");
                            }

                            break;

                        case 2:
                        case 4:
                            if (count < question.QTypeMin || count > question.QTypeMax)
                            {
                                return BadRequest(
                                    $"Min {question.QTypeMin} - Max {question.QTypeMax} items must be selected!");
                            }

                            break;
                        case 5:
                            var value = Convert.ToInt32(optionIds.FirstOrDefault());
                            model.AnswerDigit = Convert.ToDecimal(value);

                            if (question.IncrementSelect != null &&
                                ((value < question.MinSelect) || (value > question.MaxSelect) ||
                                 (value % question.IncrementSelect) != 0))
                            {
                                return BadRequest(
                                    $"Your choice must be between {question.MinSelect} - {question.MaxSelect} and multiple of {question.IncrementSelect}!");
                            }

                            break;
                    }

                var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                model.MemberId = userId;

                var result = _optionsService.SaveUserAnswers(model).Result;
                if (!result.Succeeded) throw new Exception(result.ErrorMessage);

                return Ok(model);

            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }

        }
    }
}

GuessBook.Web/Views/Shared/_HeaderPartial.cshtml
<header id="header" >
    <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark bg-dark border-bottom box-shadow mb-2">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GuessBook</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-md-inline-flex flex-md-row-reverse">
                <ul class="navbar-nav flex-grow-1 justify-content-end">
                    @*<li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>*@
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Questions" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-collapse collapse d-md-inline-flex flex-md-row-reverse">
                <ul class="nav-item dropdown no-arrow navbar-nav flex-grow-1 justify-content-end">
                    <li class="nav-item">
                        <partial name="_LoginPartial" />
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

GuessBook.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuessBook</title>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet" asp-append-version="true" />

    <!-- Bootstrap CSS File -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />

    <!-- Libraries CSS Files -->
    <link href="~/lib/fontawesome/fontawesome-free-5.12.0-web/css/all.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/ion.rangeSlider/ion.rangeSlider.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/notification/toastr.min.css" rel="stylesheet" asp-append-version="true" />


    <!-- Main Stylesheet File -->
    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/loader.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/optionsStyles.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/SortableBoxes.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/errorPage.css" rel="stylesheet" asp-append-version="true" />

    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <div>
        <partial name="_HeaderPartial" />
    </div>
    <div class="container-fluid" id="main">
        <main role="main">
            @RenderBody()
        </main>
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
    </div>
    <div class="loaderModal"></div>
    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2020 - GuessBook -
            <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-light ">
                <span>Privacy</span>
            </a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery-3.5.1.min.js" asp-append-version="true"></script>
    <script src="~/js/ion.rangeSlider-js/ion.rangeSlider.min.js" asp-append-version="true"></script>
    <script src="~/js/notification/toastr.min.js" asp-append-version="true"></script>
    <script src="~/js/notification/notifications.js" asp-append-version="true"></script>
    <script src="~/js/loader.js" asp-append-version="true"></script>
    <script src="~/js/sendOptions.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/touch-dnd.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/expiredTimeCounter.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>